### PR TITLE
Bump pprint to 0.7.1

### PR DESCRIPTION
**Pull request by tgodzik**
Pprint is currently released for 2.11/2.12/2.13 and 3

### CODE REVIEW

**Comment by kitbellew** [comment]
```
[error] java.lang.NoSuchMethodError: pprint.TPrint$.make(Lscala/Function1;)Lpprint/TPrint;
[error] 	at mdoc.internal.cli.Settings$.<clinit>(Settings.scala:303)
[error] 	at mdoc.Main$.process(Main.scala:24)
```

**Comment by tgodzik** [comment]
> ```
> [error] java.lang.NoSuchMethodError: pprint.TPrint$.make(Lscala/Function1;)Lpprint/TPrint;
> [error] 	at mdoc.internal.cli.Settings$.<clinit>(Settings.scala:303)
> [error] 	at mdoc.Main$.process(Main.scala:24)
> ```

Yeah, it seems I've run into a bit of circular dependency problem. This is caused by https://github.com/scalameta/mdoc/pull/603 which itself is blocked by this. Trying to exclude pprint from the docs project deps, but that doesn't seem to be working yet.

**Comment by tgodzik** [comment]
I removed the publishing of docusaurus for the time being, since it need the new mdoc.

**Review by kitbellew — APPROVED** [review]

**Review by keynmol — APPROVED** [review]

**Comment by kitbellew** [comment]
@keynmol וואָס פֿאַר קיינמאָל? :)

**Comment by tgodzik** [comment]
@olafurpg do you estimate any issues here?

**Review by olafurpg — APPROVED** [review]

**Comment by tgodzik** [comment]
doing a release right now since this has popped up in multiple places. I do hope that Haoyi will stop with the breaking changes :sweat_smile:

**Comment by bjaglin** [comment]
I ran into this from https://github.com/scalacenter/scalafix/pull/1522#issuecomment-1019365231: the breaking changes of pprint surface in metaconfig 0.9.16, which cannot cope with classes built against earlier metaconfig (i.e. pre https://github.com/com-lihaoyi/PPrint/pull/72).

I assume the bumps were triggered by https://github.com/scalameta/mdoc/issues/602. What about starting up a 0.10.x line so that mdoc can move forward, while maintaining a binary-compatible 0.9.x?

**Comment by tgodzik** [comment]
> I ran into this from [scalacenter/scalafix#1522 (comment)](https://github.com/scalacenter/scalafix/pull/1522#issuecomment-1019365231): the breaking changes of pprint surface in metaconfig 0.9.16, which cannot cope with classes built against earlier metaconfig (i.e. pre [com-lihaoyi/PPrint#72](https://github.com/com-lihaoyi/PPrint/pull/72)).
> 
> I assume the bumps were triggered by [scalameta/mdoc#602](https://github.com/scalameta/mdoc/issues/602). What about starting up a 0.10.x line so that mdoc can move forward, while maintaining a binary-compatible 0.9.x?

Should we actually inline pprint ourselves instead of using one that might change from time to time? This would avoid the issue I think?

**Comment by tgodzik** [comment]
I am trying that approach here https://github.com/scalameta/metaconfig/pull/154 

That should work correctly with older rules also. What do you think @bjaglin ?
