### PR TITLE
reduce risk of NoSuchMethodError when runtime version <0.9.11

### PR DESCRIPTION
**Pull request by bjaglin**
Improve forward-compatibility of df7731d

```
java.lang.NoSuchMethodError: 'void metaconfig.generic.Surface.<init>(scala.collection.immutable.List, scala.collection.immutable.List)'
  at scalafix.internal.scaluzzi.DisableConfig$.<init>(DisableConfig.scala:162)
```

Reported/discussion in https://gitter.im/scalacenter/scalafix?at=60b41af5688a2624b8bf52c0

### CODE REVIEW

**Comment by bjaglin** [comment]
cc @olafurpg

**Review by olafurpg — APPROVED** [review]
LGTM 👍 Thank you!

**Comment by bjaglin** [comment]
I just confirmed that https://github.com/vovapolu/scaluzzi built against https://github.com/scalacenter/scalafix/pull/1419 was working with Scalafix 0.9.27 (metaconfig 0.9.10).
